import Head from "next/head";
import "antd/dist/antd.css";
import "common/styles/globals.scss";
import type { AppProps } from "next/app";
import Layout from "common/containers/layout/layout";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
